puts "The students of Villains Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joeffrey Baratheon"
puts " Norman Bates"
